### ISSUE TITLE
Add Nigerian names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#97]
Add Nigerian names to the generator.

**Comment by RaturiAR7** [comment]
I would like to work on this.

**Comment by BenOvermyer** [comment]
@RaturiAR7 Alright, I'll assign it to you.

**Comment by RaturiAR7** [comment]
@BenOvermyer I have created a pull request for the issue. I am a beginner to open source and wanted to participate in hactoberfest. Please let me know if any changes are to required.

**Comment by RaturiAR7** [comment]
@BenOvermyer I thought this repo was participating in hacktoberfest but my PR with nigerian names did not count.

**Comment by BenOvermyer** [comment]
@RaturiAR7 It takes seven days after a PR is merged for it to be accepted for Hacktoberfest. See the rules here: https://hacktoberfest.com/participation/

**Comment by RaturiAR7** [comment]
Yes, I know it takes seven days but it also won't count if my PR was not labelled as hacktoberfest and hacktoberfest accepted. I think you did not label it as hacktoberfest and hacktoberfest accepted before merging my PR that's why it not appearing in my hactoberfest profile. All of my other contributions are showing in profile with a timer of 7 days from the day of getting merged.

**Comment by BenOvermyer** [comment]
One of two things must be true - either the repository has to have the topic `hacktoberfest` or the PR has to have the label `hacktoberfest-accepted`. This repository has the topic `hacktoberfest`. I submitted (and merged) a PR to this repo earlier and got credit for the PR.

I'll take another look at your PR and see if there's anything unusual about it that would cause you to not get credit.

**Comment by RaturiAR7** [comment]
Ok sir
